### ISSUE TITLE
AngrierWorldQuests' tried to call the protected function 'CastSpellByID

### ISSUE THREAD

**Issue by ala75** [GurliGebis/WoWAddon-AngrierWorldQuests#80] opened 2024-10-03 15:13 UTC
Using the latest version, I havent seen any world Quest related errors, yet, huge iprovement, ty for fixing some much stuff!! However still seeing this error pop-up when interacting with the objective frame / buttons.

Using the default interface to drop an item in for example a Delve. This can be 100% replacated for example in Kriegers Rest  Delve where you need to hold a Candle for light. The moment you drop the light by clicking the "drop" button in the ui (Objective frame) you get an error i will post below. An UI reload fixes it for the session.

6x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'CastSpellByID()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellByID'
[string "@Blizzard_ObjectiveTracker/Blizzard_ScenarioObjectiveTracker.lua"]:1090: in function <...jectiveTracker/Blizzard_ScenarioObjectiveTracker.lua:1089>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by GurliGebis** [comment] 2024-10-03 15:31
Just to be sure, you are using the `11.0.2-20241003-2` version, and you have enabled the taint workarounds in settings?

**Comment by ala75** [comment] 2024-10-03 15:35
Hi,

Yeah, this is from the TOC file :  X-Curse-Packaged-Version: 11.0.2-20241003-2

Enable Taint Workarounds is "enabled"in the options. Is there anything else i should have enabled in case i missed it?

**Comment by GurliGebis** [comment] 2024-10-03 19:25
That sounds strange.

I'm able to reproduce the issue with only my addon loaded and the taint workarounds disabled - here is what I did.
* Entered the Kriegers Rest Delve.
* Opened the map, and changed it to the Isle of Dorn map
* Tracked a world quest, and then untracked it again.
* Picked up the candle
* Tried to drop it, which caused the error.

If I then go into settings and enable the `Enable taint workarounds` settings (which reloads the UI), and then repeat the track/untrack followed by picking up and dropping the candle, it works as expected.

Can you please try again, with only BugGrabber/BugSack and AngrierWorldQuests loaded, and follow the mentioned steps above.

**Comment by SkywardShadow** [comment] 2024-10-06 02:28
I keep getting this too, but if I disable all except for AngrierWorldQuests and BugSack and have the taintless setting checked, then it no longer occurs. When I enable all, except for AngrierWorldQuests, then the next add-on to get blamed is Immersion. 

From my perspective, I think it's safe to say that this seems fixed in this add-on with the taintless setting.

**Comment by GurliGebis** [comment] 2024-10-06 06:23
Yep, that is the "beauty" of the taint system - once something breaks, every addon can get blame, since WoW doesn't report who caused the taint, just who tripped over it 🙂

**Closed by GurliGebis** 2024-10-06 06:23 UTC
