### ISSUE TITLE
ADDON_ACTION_FORBIDDEN

### ISSUE THREAD

**Issue by Ioney** [GurliGebis/WoWAddon-AngrierWorldQuests#67] opened 2024-09-08 21:08 UTC
```lua
1x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' hat versucht die geschützte Funktion 'UseQuestLogSpecialItem()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
```

Step 1: Click on a Checkbox from AWQ
Step 2: Use Special Item from Blizzard Quest List (different quest, not the checked WQ)

It is not a problem if i just click on the title of the quest on the AWQ List

**Comment by Ioney** [comment] 2024-09-08 21:17
```lua
1x [ADDON_ACTION_BLOCKED] AddOn 'AngrierWorldQuests' hat versucht die geschützte Funktion 'Button:SetPassThroughButtons()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:97: in function <...haredMapDataProviders/BonusObjectiveDataProvider.lua:92>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: in function `accessor'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:60: in function `AddCancelableCallback'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:92: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:65: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:148: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:147>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

just got this too after just using the questitem ([Lamplighter Firearm](https://www.wowhead.com/item=219943) from [Torching Lights](https://www.wowhead.com/quest=80677)) on the eggs.

this error doesnt blocks me from using the item, but the first error does.

**Comment by GurliGebis** [comment] 2024-09-09 04:44
Looks like it is a duplicate of #59, or at least causes by the same thing.
I am working on a fix for it 🙂

**Comment by GurliGebis** [comment] 2024-09-10 09:54
Please look here: https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/issues/59#issuecomment-2340199757

Update to the release mentioned, and enable the checkbox, and then report back 🙂

**Comment by WanderingFox** [comment] 2024-09-11 18:31
weirdly i only have the taint issue if I _do_ check the box

**Comment by martinboy1974** [comment] 2024-09-26 17:44
I also still have the issue. I made sure to enable taint workaround and made sure function was called. Reloaded the UI. As soon as I clicked an item in the questtracker, I got this error and only reloading the UI again cleared the error.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by GurliGebis** [comment] 2024-09-26 20:54
Okay, so let me make sure I get this right.
You track a world quest, followed by clicking a quest button on the tracker?

**Comment by martinboy1974** [comment] 2024-09-26 22:42
> Okay, so let me make sure I get this right. You track a world quest, followed by clicking a quest button on the tracker?

Yes, after enabling taint workaround and reloading UI, I picked up a quest that had a on use item in the questtrack. As soon as I clicked the item in the tracker, I got the LUA error. Had to reload UI again to be able to use the item.

**Comment by GurliGebis** [comment] 2024-10-03 08:47
Okay, this one threw me for a loop for quiet a while.

I managed to track it down to only happening when you untrack a world quest, not when you track it.
This pointed me to this line: https://github.com/Gethe/wow-ui-source/blob/5076663b5454de9e7522320994ea7cc15b2a961c/Interface/AddOns/Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua#L457C2-L457C38

So, when a world quest is untracked, the entire objective tracker is refreshed, which taints it (since it is being called indirectly from this code).

So to workaround it, I have overwritten both the track and untrack functions (since they share local variables), and removed the call to refresh the tracker (looks like it is working just fine with it not being called).

New release incoming shortly.

**Closed** 2024-10-03 08:49 UTC
