### ISSUE TITLE
11.0.2-20240910-2 Options not saving

### ISSUE THREAD

**Issue by Shauren** [GurliGebis/WoWAddon-AngrierWorldQuests#70] opened 2024-09-10 21:26 UTC
First four options cannot be unchecked - they reset themselves after closing options panel

![obraz](https://github.com/user-attachments/assets/85328021-09b5-4875-bac6-2424e7da7559)

**Comment by GurliGebis** [comment] 2024-09-11 05:05
Interresting, I take a look at it 🙂
Does none of the other settings save for you?

**Comment by GurliGebis** [comment] 2024-09-11 07:57
I found the issue and have a fix ready - will release it later today.

The issue is that "false" and "nil" are the same in Lua ... so now we have to store settings as strings instead.

**Comment by GurliGebis** [comment] 2024-09-11 08:36
I have released `11.0.2-20240911-1` with the fix for this 🙂

**Closed** 2024-09-11 08:35 UTC

**Comment by Dairyman** [comment] 2024-09-11 16:15
Sorry but `nil` and `false` are not the same 😉. The problem is that false and nil are not trueish so
```Lua
local f = false
local n = nil

-- these two are both false
if n then end
if f then end

-- n is false but f is true
if n == false then end
if f == false then end

-- n is true but f is false
if n == nil then end
if f == nil then end
```
You need to check directly for false or nil in such situation.

**Comment by GurliGebis** [comment] 2024-09-11 16:23
I see, good to know 🙂
I'm not going to change it back though, since it works with saving them as strings.
